name = "robotsrevenge"
compatibility_date = "2026-02-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "robotsrevenge-results"
database_id = "c948c266-7d1b-4c24-aeca-a172d291ccd3"
preview_database_id = "c948c266-7d1b-4c24-aeca-a172d291ccd3"
